// Icons in `icons.svg` that break a rule of `docs/style-guide/icons.md` today. Checked by
// `iconStyle.test.ts`: remove an id once it is fixed (the test fails until you do), and never add one.
// The lists are the icon cleanup backlog of epic #95.

export type StyleRule =
  | 'canvas'
  | 'colour'
  | 'strokeWidth'
  | 'strokeEnds'
  | 'secondaryTone'
  | 'structure'
  | 'coordinates'
  | 'naming'

export const KNOWN_VIOLATIONS: Record<StyleRule, readonly string[]> = {
  // viewBox 0 0 16 16, width and height 16 (1)
  canvas: ['expanded_node'],
  // currentColor only; `*_color` brand marks are exempt (7)
  colour: [
    'activity',
    'bottom_panel',
    'eye_crossed',
    'folder_add',
    'graph_add',
    'icon/lock',
    'right_panel',
  ],
  // stroke width 2 (1.5 only for a detail inside a filled icon) (14)
  strokeWidth: [
    'document',
    'help',
    'info',
    'join2-1',
    'local_scope2',
    'navigate_breadcrumb',
    'properties',
    'schedule',
    'sessions',
    'text_input',
    'tidy_up',
    'transform4',
    'union',
    'versions',
  ],
  // round caps and round joins on every stroke (21)
  strokeEnds: [
    'accessed_by_projects',
    'at',
    'braces',
    'copy',
    'document',
    'enso_logo',
    'grab',
    'history',
    'icon/lock',
    'info',
    'join2-1',
    'local_scope2',
    'marketplace',
    'root',
    'select',
    'shortcut',
    'text_input',
    'tidy_up',
    'union',
    'versions',
    'zoom',
  ],
  // one secondary tone, opacity 0.3 (47)
  secondaryTone: [
    'accessed_by_projects',
    'array_new',
    'array_new2',
    'column_add',
    'column_remove',
    'compass',
    'data_download',
    'data_input',
    'data_output',
    'data_upload',
    'docs',
    'expanded_node',
    'find',
    'geo_map_distance',
    'heatmap',
    'input_number',
    'join',
    'join2-1',
    'join_full',
    'join_inner',
    'join_left_exclusive',
    'join_left_outer',
    'join_right_exclusive',
    'join_right_outer',
    'keyboard_shortcuts',
    'local_scope2',
    'logout',
    'map_row',
    'marketplace',
    'people',
    'people_settings',
    'root',
    'row_add',
    'row_remove',
    'select_column',
    'select_row',
    'sort_ascending',
    'sort_descending',
    'table_clean',
    'table_edit',
    'text',
    'text2',
    'text_input',
    'time',
    'union',
    'unstable',
    'workflow_play',
  ],
  // no transform, clip-path, mask, defs, gradient or inner ids (14)
  structure: [
    'activity',
    'apple_color',
    'array_new2',
    'bottom_panel',
    'data_download',
    'data_upload',
    'eye_crossed',
    'folder_add',
    'github_color',
    'graph_add',
    'icon/lock',
    'logout',
    'right_panel',
    'shortcut',
  ],
  // at most 2 decimals (155)
  coordinates: [
    '3_dot_menu',
    'activity',
    'align_bottom',
    'align_center',
    'align_left',
    'align_right',
    'align_top',
    'apple_color',
    'arrow_circle_left',
    'arrow_left',
    'arrow_right',
    'at',
    'bold',
    'bottom_panel',
    'braces',
    'brush',
    'bullet-list',
    'calendar',
    'check',
    'clone',
    'close',
    'cloud',
    'cloud_from',
    'cloud_to',
    'code',
    'columns_increasing',
    'comment',
    'compass',
    'compliance',
    'connector',
    'connector_add',
    'create_account',
    'credential_add',
    'credit_card',
    'datetime',
    'default_user',
    'docs',
    'document',
    'drive',
    'duplicate',
    'edit',
    'email',
    'enso_logo',
    'error',
    'exclamation',
    'exit_fullscreen',
    'expanded_node',
    'eye',
    'eye_crossed',
    'find',
    'folder',
    'folder_add',
    'folder_add_small',
    'folder_closed',
    'folder_opened',
    'folder_small',
    'fullscreen',
    'ghost',
    'github_color',
    'google_color',
    'grab',
    'graph',
    'graph_add',
    'graph_editor',
    'group',
    'group_rename',
    'header1',
    'header2',
    'header3',
    'heatmap',
    'help',
    'history',
    'home2',
    'icon/lock',
    'image',
    'info',
    'input_number',
    'italic',
    'join2-1',
    'join_full',
    'join_inner',
    'join_left_exclusive',
    'join_left_outer',
    'join_right_exclusive',
    'join_right_outer',
    'key',
    'key_add',
    'local_scope4',
    'location',
    'log',
    'math',
    'metadata',
    'microsoft_color',
    'mixed',
    'navigate_back',
    'navigate_breadcrumb',
    'navigate_forward',
    'navigate_up',
    'not_exclamation',
    'not_paragraph',
    'numbered-list',
    'open',
    'open_in_file_browser',
    'operators',
    'order',
    'paint_palette',
    'panic',
    'paragraph',
    'paste',
    'path2',
    'people',
    'people_settings',
    'points',
    'properties',
    'quote',
    'random',
    'recent',
    'redo',
    'refresh',
    'restore',
    'right_panel',
    'robot',
    'schedule',
    'scissors',
    'select',
    'select_column',
    'sessions',
    'settings',
    'show_all',
    'space_default',
    'space_tight',
    'space_wide',
    'space_zero',
    'spatial',
    'split',
    'system',
    'tab_close',
    'table',
    'table_clean',
    'tag',
    'temp',
    'text3',
    'tidy_up',
    'time',
    'time2',
    'trash',
    'trash_small',
    'undo',
    'unstable',
    'untrash',
    'vector_add',
    'versions',
    'warning',
    'workflow_play',
    'zoom',
  ],
  // snake_case, no iteration numbers, no paths (16)
  naming: [
    '3_dot_menu',
    'array_new2',
    'bullet-list',
    'copy2',
    'home2',
    'icon/lock',
    'join2-1',
    'local_scope2',
    'local_scope4',
    'numbered-list',
    'parse3',
    'path2',
    'text2',
    'text3',
    'time2',
    'transform4',
  ],
}
